spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:log4jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis.host: ${REDIS_HOST}
    redis.port: ${REDIS_PORT}
    mongodb.uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@yeohaeng-ttukttak.q7ycwnj.mongodb.net/local_db?retryWrites=true&w=majority&appName=yeohaeng-ttukttak

  mail:
    host: smtp.gmail.com
    port: 587
    username: yeohaeng.ttukttak@gmail.com
    password: ${SMTP_PASSWORD}
    properties.mail.smtp:
      starttls.enable: true
      auth: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health.enabled: true

logging.level:
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    jdbc.resultsettable: off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off

host:
  storage:
    local: ${LOCAL_STORAGE_PATH}

secret:
  token: ${TOKEN_SECRET}