spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:log4jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health.enabled: true

logging.level:
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    jdbc.resultsettable: off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off

path:
  storage:
    local: ${LOCAL_STORAGE_PATH}