version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
  
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: stop_application.sh
      timeout: 60
  ApplicationStart: 
    - location: start_application.sh
      timeout: 60
      runas: ubuntu