name: Continuous Deployment(CD)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    environment: development
    name: Deploy Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Grant Execution Permission to gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Compress project to deploy
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      - name: Upload to remote blob container
        run: aws s3 cp --region $AWS_DEFAULT_REGION ./$GITHUB_SHA.zip s3://$AWS_DEPLOY_BUCKET/$GITHUB_SHA.zip
