name: Continuous Deployment(CD)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: 
  id-token: write  # OIDC JWT 요청을 위한 권한 부여
  contents: read   # actions/checkout 실행을 위한 권한
      
jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build # 빌드 작업이 성공적으로 완료된 후 실행

    steps:
      - uses: actions/checkout@v3

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          path: deploy
          name: application # 빌드 작업에서 업로드한 아티팩트 다운로드

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Compress application for deployment
        run: zip -r ./$GITHUB_SHA.zip ./deploy # 다운로드한 아티팩트 압축
        
      - name: Upload to remote blob container
        env:
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://$AWS_BUCKET/$GITHUB_SHA.zip
