name: Build Project

on:
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        type: boolean
        default: true
      run_tests: # 테스트 실행 여부를 결정하는 입력 변수 추가
        required: false
        type: boolean
        default: false # 기본값은 false로 설정

jobs:
  build:
    runs-on: ubuntu-latest
    # 테스트를 위한 Postgres/PostGIS 서비스 설정
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3 # 소스 코드 체크아웃

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle # Gradle 캐시 설정

      - name: Grant Execution Permission to gradlew
        run: chmod +x gradlew # gradlew 실행 권한 부여

      - name: Conditionally Build with or without Tests
        run: |
          if [ "${{ inputs.run_tests }}" = "true" ]; then
            ./gradlew build
          else
            ./gradlew build -x test
          fi
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: testdb
          DB_USERNAME: testuser
          DB_PASSWORD: testpassword

      - name: Upload build artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: ./build/libs/*.jar
